--INSERT INTO Employees(EMP_ID,EMP_NAME,DEPARTMENT,SALARY) VALUES(6,'Frank Green','HR',55000);
INSERT INTO Employees(EMP_ID,EMP_NAME,DEPARTMENT) VALUES(7,'Grace Hall','IT');
SELECT * FROM Employees;